services:
  membershipadmin-test:
    container_name: membershipadmin-test
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    restart: always
