services:
  membershipadmin-prod:
    container_name: membershipadmin-prod
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
